module.exports.User = require('./user.model');
module.exports.Employee = require('./employee.model');
module.exports.Token = require('./token.model');
module.exports.Settings = require('./settings.model');
module.exports.Role = require('./role.model');
module.exports.Cms = require('./cms.model');
module.exports.Movies = require('./movies.model');
module.exports.Hotels = require('./hotels.model'); // exporting hotel module
module.exports.Notifications = require('./notifications.model');
